### ISSUE TITLE
plugin.apply is not a function. 

### ISSUE THREAD

**Issue by h-tendy** [Moxio/markdown-it-fancy-lists#1]
hello! Thanks for writing this plugin, will be very useful once I get it to work. 

I'm having a problem using this though (in combination with multiple other plugins). When I do, it gives an error. Any clues? I'm just doing a chain of `use` calls: 

``` js
let MarkdownIt = new require('markdown-it')({
    linkify: true,
    html: true
}).use(require('markdown-it-fancy-lists')).use(require('markdown-it-bracketed-spans')).use(require('markdown-it-attrs')).use(require('markdown-it-container'), 'code').use(require('markdown-it-container'), 'indent1').use(require('markdown-it-container'), 'indent2').use(require('markdown-it-container'), 'indent3').use(require('markdown-it-highlightjs')).use(markdownItMermaid).use(require('markdown-it-plantuml'), {imageFormat: 'png'}).use(require('markdown-it-container'), 'slide');
```

Error: 
```
TypeError: plugin.apply is not a function
MarkdownIt.push../node_modules/markdown-it/lib/index.js.MarkdownIt.use
C:/cygwin64/home/tendy/datagroom-ui/node_modules/markdown-it/lib/index.js:516
  513 | /*, params, ... */
  514 | ) {
  515 |   var args = [this].concat(Array.prototype.slice.call(arguments, 1));
> 516 |   plugin.apply(plugin, args);
  517 |   return this;
  518 | };
  519 | /** internal
```

This is for an open-source project called datagroom (https://github.com/h-tendy/datagroom-gateway)

Thanks so much.

**Comment by FritsvanCampen** [comment]
Hi! Thanks for the showing interest in the plugin.

I haven't seen this error before. If I had to make a guess on line 516 `plugin` is not a function. Maybe one of the plugins doesn't return a function directly.

Can you figure out which plugin causes this error? You can remove the `.use()`-calls and add them one by one until you get this error.

**Comment by FritsvanCampen** [comment]
I think I see what the problem is.

Try:

```
.use(require('markdown-it-fancy-lists').markdownItFancyListPlugin)
```

Since `require('markdown-it-fancy-lists')` doesn't return a function directly.

**Comment by h-tendy** [comment]
Thanks @FritsvanCampen that worked! I have one more query on the rendering, will open another ticket.
