### ISSUE TITLE
Rendering sub-lists. 

### ISSUE THREAD

**Issue by h-tendy** [Moxio/markdown-it-fancy-lists#2]
The documentation example doesn't seem to render correctly, is this a known issue? : 
``` 
c. charlie
#. delta
   iv) subfour
   #) subfive
   #) subsix
#. echo
```
Renders like this: 

![image](https://user-images.githubusercontent.com/40791586/131777352-c4704e57-ec9d-4e9f-8fd3-6f4dbdd651a6.png)

HTML is this: 
``` HTML
<ol type="a" start="3">
<li>charlie</li>
<li>delta
iv) subfour
<ol>
<li>subfive</li>
<li>subsix</li>
</ol>
</li>
<li>echo</li>
</ol>
```

Another example: 

``` md
* Some list first. 
a. One more list. 
    A. Can I get one more list here?
    B. What about this? 
    Let us see one more sub-level
    i. Roman 1, 
    i. Roman 2
a. One more list. 
```
Renders to: 
![image](https://user-images.githubusercontent.com/40791586/131777609-7eee7627-5571-4f6f-99cf-ed68220ff3e1.png)

HTML as: 
``` HTML
<ul>
<li>Some list first.</li>
</ul>
<ol type="a">
<li>One more list.
A. Can I get one more list here?
B. What about this?
Let us see one more sub-level
<ol type="i">
<li>Roman 1,</li>
<li>Roman 2</li>
</ol>
</li>
<li>One more list.</li>
</ol>
```
I guess the second level sub-list is not rendering properly...

**Comment by FritsvanCampen** [comment]
Hi, thanks for the report.

I can confirm both cases do not produce the expected result - the tab-character in the 2nd example was unintentional I presume but even without it it doesn't produce the expected result.

I'll raise a ticket internally to work on it, it may take a while.
You're more than welcome to submit a PR in the meantime.

**Comment by h-tendy** [comment]
Actually, reading the code briefly, I found that there is a comment that you need two spaces after capital letters. With that, the problem is mitigated. Not sure why the two spaces are required for capital letters. 

I did further tests. In the below, see the 'doesn't render correctly' comment. Rest all renders good! 

``` md
a. One more list. 
   iv. Can I get one more list here?
    i. What about this? 
    	b. One more nested list. 
        a. Again. 
            X.  Two spaces for caps after `.` 
            X.  Two spaces for caps again. 
        a. Back up. 
    
    Let us see one more sub-level after a paragraph in the middle of a list. When it starts with `i.` it is good. 
    i. Roman 1, 
    i. Roman 2
    
    One more paragraph break in the middle. This time, start with `c.` This doesn't render correctly: 
    c. item a
    c. item b
    
a. One more list. 

A.  A caps list. 
A.  Another. 
```

![image](https://user-images.githubusercontent.com/40791586/131861677-2625f134-2797-448c-9868-16c67dc39a1e.png)


Your documentation example works when it looks like this. Instead of `iv`, use `i` and it recognizes it correctly: 

``` md
c. charlie
#. delta
   i) subfour
   #) subfive
   #) subsix
#. echo
```
![image](https://user-images.githubusercontent.com/40791586/131861741-a5e3fef8-e64c-4b02-a2ad-347de20e1c26.png)

Overall, these are minor issues. Only the two-spaces-when-using-caps is not intuitive... 

THANKS MUCH for rapid responses!

**Comment by FritsvanCampen** [comment]
> Actually, reading the code briefly, I found that there is a comment that you need two spaces after capital letters. With that, the problem is mitigated. Not sure why the two spaces are required for capital letters.

Ah yes! I remember this. See the footnote in the pandoc spec: https://pandoc.org/MANUAL.html#fn1

I will still look at the `iv)` startnum bug. There might be a reason why that specific sublist doesn't work but it's in the readme so either we fix it or we change the readme.

**Comment by FritsvanCampen** [comment]
I figured out what is causing the issue.

The sublist input text is essentially:

```markdown
delta
iv) subfour
#) subfive
#) subsix
```

And according to the test "does not allow subsequent numbers to interrupt paragraphs" this is not a valid way to start a list. The `#` on the next line then _is_ because it can be interpreted as a list starting at 1.

This markdown _will_ produce the intended output:

```markdown
c. charlie
#. delta

   iv) subfour
   #) subfive
   #) subsix
#. echo
```

Do you have an opinion on this behavior?

**Comment by FritsvanCampen** [comment]
pandoc https://pandoc.org/try/ and commonmark https://spec.commonmark.org/dingus/ don't agree on how to render lists, whether lists are allowed to interrupt paragraphs, and are not internally consistent on whether this is allowed in a nested context.

This plugin now allows lists to always interrupt paragraphs.

The example in the readme now renders as you would expect.
